all: main

main: main.cpp Visual/screen.cpp controller.cpp StateManagement/state.cpp StateManagement/command.cpp
	g++ -o main main.cpp Visual/screen.cpp controller.cpp StateManagement/state.cpp StateManagement/command.cpp -lncurses